### ISSUE TITLE
add LICENSE

### ISSUE THREAD

**Issue by wayneashleyberry** [azer/snakecase#6]
This project is missing a license which might make it difficult for some organisations to use it.

**Comment by azer** [comment]
done

**Comment by pasztorpisti** [comment]
In my opinion you should consider using the [`MIT-0`](https://spdx.org/licenses/MIT-0.html) license when it comes to copy-pastable "public domain" source code.

It's a relatively new license but its text has been derived from one of the most popular permissive licenses that is legally tested and according to the [SPDX Licence List](https://spdx.org/licenses/) the MIT-0 is OSI approved. This page describes the motivation behind the license: https://github.com/aws/mit-0

I agree with the philosophy of WTFPL when it comes to legal bullshit but in practice most projects are better off with battle-tested legal text.

**Comment by azer** [comment]
@pasztorpisti thanks for the suggestion. I'm happy with WTFPL though.
